# Generated by Django 5.0.3 on 2024-04-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default='No description available', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.URLField(default='https://www.google.com'),
        ),
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(default='No title', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='No name', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='no_of_guest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
