# Generated by Django 5.0.3 on 2024-04-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_category_menu_description_menu_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='inventory',
        ),
    ]
