# Generated by Django 5.0.3 on 2024-04-08 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_menu_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Uncategorized', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='{%static "assets/menu_images"%}', upload_to='menu_images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.category'),
        ),
    ]
