# Generated by Django 5.0.3 on 2024-04-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_category_alter_menu_image_alter_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='menu_images'),
        ),
    ]
